"""Backups of the configuration files uniscript changes.

Every session gets its own directory. The original path is mirrored in the
tree, so the copy stays readable, and the generated restore.sh undoes every
change in a single run.
"""

from __future__ import annotations

import json
import shlex
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass(frozen=True)
class BackupEntry:
    original: str
    copy: str | None
    existed: bool
    mode: str
    root: bool
    timestamp: str


class BackupStore:
    def __init__(self, root: Path, session: str | None = None) -> None:
        self.session = session or datetime.now().strftime("%Y%m%d-%H%M%S")
        self.root = root / self.session
        self.entries: list[BackupEntry] = []

    @property
    def files_dir(self) -> Path:
        return self.root / "files"

    def _copy_path(self, original: Path) -> Path:
        return self.files_dir / original.as_posix().lstrip("/")

    def record(
        self,
        original: Path,
        content: bytes | None,
        *,
        mode: str = "0644",
        root: bool = True,
    ) -> BackupEntry:
        """Store a copy. content=None means the file did not exist."""
        timestamp = datetime.now().isoformat(timespec="seconds")
        if content is None:
            entry = BackupEntry(str(original), None, False, mode, root, timestamp)
        else:
            destination = self._copy_path(original)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)
            entry = BackupEntry(str(original), str(destination), True, mode, root, timestamp)
        self.entries.append(entry)
        self._flush()
        return entry

    def _flush(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        manifest = self.root / "manifest.json"
        manifest.write_text(
            json.dumps([entry.__dict__ for entry in self.entries], indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        self._write_restore_script()

    def _write_restore_script(self) -> None:
        # No set -e: one failed path must not stop the rest from being restored.
        lines = [
            "#!/usr/bin/env bash",
            f"# Generated by uniscript. Reverts the changes made in session {self.session}.",
            "set -uo pipefail",
            "",
            'SUDO=""',
            'if [ "$(id -u)" -ne 0 ]; then',
            '    SUDO="sudo"',
            "fi",
            "failed=0",
            "",
            "restore_file() {",
            '    local privileged="$1" mode="$2" copy="$3" target="$4" prefix=""',
            '    if [ "$privileged" = "1" ]; then prefix="$SUDO"; fi',
            '    if ! $prefix install -D -m "$mode" -- "$copy" "$target"; then',
            "        printf 'failed to restore %s\\n' \"$target\" >&2",
            "        failed=$((failed + 1))",
            "    fi",
            "}",
            "",
            "remove_file() {",
            '    local privileged="$1" target="$2" prefix=""',
            '    if [ "$privileged" = "1" ]; then prefix="$SUDO"; fi',
            '    if ! $prefix rm -f -- "$target"; then',
            "        printf 'failed to remove %s\\n' \"$target\" >&2",
            "        failed=$((failed + 1))",
            "    fi",
            "}",
            "",
        ]
        for entry in self.entries:
            original = shlex.quote(entry.original)
            privileged = "1" if entry.root else "0"
            if entry.existed and entry.copy:
                copy = shlex.quote(entry.copy)
                mode = shlex.quote(entry.mode)
                lines.append(f"restore_file {privileged} {mode} {copy} {original}")
            else:
                lines.append(f"remove_file {privileged} {original}")
        lines.extend(
            [
                "",
                'if [ "$failed" -ne 0 ]; then',
                "    printf 'Failed to restore %s files.\\n' \"$failed\" >&2",
                "    exit 1",
                "fi",
                'echo "Restored. Some changes need a service or system restart to take effect."',
            ]
        )
        script = self.root / "restore.sh"
        script.write_text("\n".join(lines) + "\n", encoding="utf-8")
        script.chmod(0o755)

    def summary(self) -> str:
        if not self.entries:
            return "no backups in this session"
        return f"{len(self.entries)} files in {self.root}"


@dataclass(frozen=True)
class RestoreSession:
    """A past session whose file changes can be reverted with its restore.sh."""

    name: str
    label: str
    path: Path
    script: Path
    files: list[str]
    # Whether restoring needs sudo; True when the manifest cannot be read.
    needs_root: bool = True


def session_label(name: str) -> str:
    try:
        return datetime.strptime(name, "%Y%m%d-%H%M%S").strftime("%Y-%m-%d %H:%M:%S")
    except ValueError:
        return name


def list_restore_sessions(backups_root: Path) -> list[RestoreSession]:
    """Every session with a restore script, newest first.

    Sessions that changed no files write nothing to disk and therefore never
    show up here; a broken manifest still yields the session, just without
    the file list.
    """
    if not backups_root.is_dir():
        return []
    sessions: list[RestoreSession] = []
    for entry in sorted(backups_root.iterdir(), reverse=True):
        script = entry / "restore.sh"
        if not entry.is_dir() or not script.is_file():
            continue
        files: list[str] = []
        needs_root = True
        try:
            manifest = json.loads((entry / "manifest.json").read_text(encoding="utf-8"))
            files = list(dict.fromkeys(item["original"] for item in manifest))
            needs_root = any(item.get("root", True) for item in manifest)
        except (OSError, ValueError, KeyError, TypeError):
            pass
        sessions.append(
            RestoreSession(
                entry.name, session_label(entry.name), entry, script, files, needs_root
            )
        )
    return sessions
